# Generated by Django 4.1.2 on 2022-10-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='id',
            field=models.CharField(default='it_000', editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leg',
            name='id',
            field=models.CharField(default='leg_000', editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
