# Generated by Django 4.1.2 on 2022-10-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_itinerary_id_alter_leg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='id',
            field=models.CharField(default='it_000', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leg',
            name='id',
            field=models.CharField(default='leg_000', max_length=20, primary_key=True, serialize=False),
        ),
    ]
