# Generated by Django 4.1.2 on 2022-10-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_itinerary_id_alter_leg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leg',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='legs',
            field=models.ManyToManyField(related_name='leg', to='flights.leg'),
        ),
    ]
